// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/shortlink.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages for CreateShortURL
type CreateShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                     // The original URL to shorten
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User ID (optional, can be empty)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLRequest) Reset() {
	*x = CreateShortURLRequest{}
	mi := &file_proto_shortlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLRequest) ProtoMessage() {}

func (x *CreateShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLRequest.ProtoReflect.Descriptor instead.
func (*CreateShortURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateShortURLRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`                 // The generated short URL
	AlreadyExists bool                   `protobuf:"varint,2,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"` // True if URL was already shortened
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLResponse) Reset() {
	*x = CreateShortURLResponse{}
	mi := &file_proto_shortlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLResponse) ProtoMessage() {}

func (x *CreateShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLResponse.ProtoReflect.Descriptor instead.
func (*CreateShortURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *CreateShortURLResponse) GetAlreadyExists() bool {
	if x != nil {
		return x.AlreadyExists
	}
	return false
}

// Request/Response messages for GetOriginalURL
type GetOriginalURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"` // The short URL to resolve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLRequest) Reset() {
	*x = GetOriginalURLRequest{}
	mi := &file_proto_shortlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLRequest) ProtoMessage() {}

func (x *GetOriginalURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLRequest.ProtoReflect.Descriptor instead.
func (*GetOriginalURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalURLRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetOriginalURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` // The original URL
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`                               // True if URL was found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalURLResponse) Reset() {
	*x = GetOriginalURLResponse{}
	mi := &file_proto_shortlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalURLResponse) ProtoMessage() {}

func (x *GetOriginalURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalURLResponse.ProtoReflect.Descriptor instead.
func (*GetOriginalURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GetOriginalURLResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Request/Response messages for CreateShortURLBatch
type CreateShortURLBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*BatchURLItem        `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`                   // List of URLs to shorten
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLBatchRequest) Reset() {
	*x = CreateShortURLBatchRequest{}
	mi := &file_proto_shortlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLBatchRequest) ProtoMessage() {}

func (x *CreateShortURLBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateShortURLBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{4}
}

func (x *CreateShortURLBatchRequest) GetUrls() []*BatchURLItem {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *CreateShortURLBatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateShortURLBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchURLResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // Results for each URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLBatchResponse) Reset() {
	*x = CreateShortURLBatchResponse{}
	mi := &file_proto_shortlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLBatchResponse) ProtoMessage() {}

func (x *CreateShortURLBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateShortURLBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{5}
}

func (x *CreateShortURLBatchResponse) GetResults() []*BatchURLResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type BatchURLItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Unique identifier for this item
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`       // The original URL to shorten
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchURLItem) Reset() {
	*x = BatchURLItem{}
	mi := &file_proto_shortlink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchURLItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLItem) ProtoMessage() {}

func (x *BatchURLItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLItem.ProtoReflect.Descriptor instead.
func (*BatchURLItem) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{6}
}

func (x *BatchURLItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchURLItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type BatchURLResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`  // Matches the correlation_id from request
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`                 // The generated short URL
	AlreadyExists bool                   `protobuf:"varint,3,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"` // True if URL was already shortened
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchURLResult) Reset() {
	*x = BatchURLResult{}
	mi := &file_proto_shortlink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchURLResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLResult) ProtoMessage() {}

func (x *BatchURLResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLResult.ProtoReflect.Descriptor instead.
func (*BatchURLResult) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{7}
}

func (x *BatchURLResult) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchURLResult) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *BatchURLResult) GetAlreadyExists() bool {
	if x != nil {
		return x.AlreadyExists
	}
	return false
}

// Request/Response messages for GetUserURLs
type GetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsRequest) Reset() {
	*x = GetUserURLsRequest{}
	mi := &file_proto_shortlink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsRequest) ProtoMessage() {}

func (x *GetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserURLItem         `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"` // List of user's URLs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsResponse) Reset() {
	*x = GetUserURLsResponse{}
	mi := &file_proto_shortlink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse) ProtoMessage() {}

func (x *GetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserURLsResponse) GetUrls() []*UserURLItem {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UserURLItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`          // The short URL
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` // The original URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLItem) Reset() {
	*x = UserURLItem{}
	mi := &file_proto_shortlink_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLItem) ProtoMessage() {}

func (x *UserURLItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLItem.ProtoReflect.Descriptor instead.
func (*UserURLItem) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{10}
}

func (x *UserURLItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserURLItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// Request/Response messages for DeleteUserURLs
type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrls     []string               `protobuf:"bytes,1,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"` // List of short URLs to delete
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // User ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_proto_shortlink_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserURLsRequest) GetShortUrls() []string {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

func (x *DeleteUserURLsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // True if deletion was successful
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsResponse) Reset() {
	*x = DeleteUserURLsResponse{}
	mi := &file_proto_shortlink_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsResponse) ProtoMessage() {}

func (x *DeleteUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserURLsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request/Response messages for Ping
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_shortlink_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{13}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"` // True if service is healthy
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Optional status message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_shortlink_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{14}
}

func (x *PingResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request/Response messages for GetStats (internal API)
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_shortlink_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{15}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`   // Number of shortened URLs
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"` // Number of users
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_shortlink_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{16}
}

func (x *GetStatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetStatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_proto_shortlink_proto protoreflect.FileDescriptor

const file_proto_shortlink_proto_rawDesc = "" +
	"\n" +
	"\x15proto/shortlink.proto\x12\tshortlink\"B\n" +
	"\x15CreateShortURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\\\n" +
	"\x16CreateShortURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12%\n" +
	"\x0ealready_exists\x18\x02 \x01(\bR\ralreadyExists\"4\n" +
	"\x15GetOriginalURLRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"Q\n" +
	"\x16GetOriginalURLResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"b\n" +
	"\x1aCreateShortURLBatchRequest\x12+\n" +
	"\x04urls\x18\x01 \x03(\v2\x17.shortlink.BatchURLItemR\x04urls\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"R\n" +
	"\x1bCreateShortURLBatchResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.shortlink.BatchURLResultR\aresults\"X\n" +
	"\fBatchURLItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"{\n" +
	"\x0eBatchURLResult\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\x12%\n" +
	"\x0ealready_exists\x18\x03 \x01(\bR\ralreadyExists\"-\n" +
	"\x12GetUserURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"A\n" +
	"\x13GetUserURLsResponse\x12*\n" +
	"\x04urls\x18\x01 \x03(\v2\x16.shortlink.UserURLItemR\x04urls\"M\n" +
	"\vUserURLItem\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"O\n" +
	"\x15DeleteUserURLsRequest\x12\x1d\n" +
	"\n" +
	"short_urls\x18\x01 \x03(\tR\tshortUrls\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"2\n" +
	"\x16DeleteUserURLsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\r\n" +
	"\vPingRequest\"B\n" +
	"\fPingResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fGetStatsRequest\"<\n" +
	"\x10GetStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users2\xc9\x04\n" +
	"\x10ShortLinkService\x12U\n" +
	"\x0eCreateShortURL\x12 .shortlink.CreateShortURLRequest\x1a!.shortlink.CreateShortURLResponse\x12U\n" +
	"\x0eGetOriginalURL\x12 .shortlink.GetOriginalURLRequest\x1a!.shortlink.GetOriginalURLResponse\x12d\n" +
	"\x13CreateShortURLBatch\x12%.shortlink.CreateShortURLBatchRequest\x1a&.shortlink.CreateShortURLBatchResponse\x12L\n" +
	"\vGetUserURLs\x12\x1d.shortlink.GetUserURLsRequest\x1a\x1e.shortlink.GetUserURLsResponse\x12U\n" +
	"\x0eDeleteUserURLs\x12 .shortlink.DeleteUserURLsRequest\x1a!.shortlink.DeleteUserURLsResponse\x127\n" +
	"\x04Ping\x12\x16.shortlink.PingRequest\x1a\x17.shortlink.PingResponse\x12C\n" +
	"\bGetStats\x12\x1a.shortlink.GetStatsRequest\x1a\x1b.shortlink.GetStatsResponseB$Z\"github.com/BazNick/shortlink/protob\x06proto3"

var (
	file_proto_shortlink_proto_rawDescOnce sync.Once
	file_proto_shortlink_proto_rawDescData []byte
)

func file_proto_shortlink_proto_rawDescGZIP() []byte {
	file_proto_shortlink_proto_rawDescOnce.Do(func() {
		file_proto_shortlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortlink_proto_rawDesc), len(file_proto_shortlink_proto_rawDesc)))
	})
	return file_proto_shortlink_proto_rawDescData
}

var file_proto_shortlink_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_shortlink_proto_goTypes = []any{
	(*CreateShortURLRequest)(nil),       // 0: shortlink.CreateShortURLRequest
	(*CreateShortURLResponse)(nil),      // 1: shortlink.CreateShortURLResponse
	(*GetOriginalURLRequest)(nil),       // 2: shortlink.GetOriginalURLRequest
	(*GetOriginalURLResponse)(nil),      // 3: shortlink.GetOriginalURLResponse
	(*CreateShortURLBatchRequest)(nil),  // 4: shortlink.CreateShortURLBatchRequest
	(*CreateShortURLBatchResponse)(nil), // 5: shortlink.CreateShortURLBatchResponse
	(*BatchURLItem)(nil),                // 6: shortlink.BatchURLItem
	(*BatchURLResult)(nil),              // 7: shortlink.BatchURLResult
	(*GetUserURLsRequest)(nil),          // 8: shortlink.GetUserURLsRequest
	(*GetUserURLsResponse)(nil),         // 9: shortlink.GetUserURLsResponse
	(*UserURLItem)(nil),                 // 10: shortlink.UserURLItem
	(*DeleteUserURLsRequest)(nil),       // 11: shortlink.DeleteUserURLsRequest
	(*DeleteUserURLsResponse)(nil),      // 12: shortlink.DeleteUserURLsResponse
	(*PingRequest)(nil),                 // 13: shortlink.PingRequest
	(*PingResponse)(nil),                // 14: shortlink.PingResponse
	(*GetStatsRequest)(nil),             // 15: shortlink.GetStatsRequest
	(*GetStatsResponse)(nil),            // 16: shortlink.GetStatsResponse
}
var file_proto_shortlink_proto_depIdxs = []int32{
	6,  // 0: shortlink.CreateShortURLBatchRequest.urls:type_name -> shortlink.BatchURLItem
	7,  // 1: shortlink.CreateShortURLBatchResponse.results:type_name -> shortlink.BatchURLResult
	10, // 2: shortlink.GetUserURLsResponse.urls:type_name -> shortlink.UserURLItem
	0,  // 3: shortlink.ShortLinkService.CreateShortURL:input_type -> shortlink.CreateShortURLRequest
	2,  // 4: shortlink.ShortLinkService.GetOriginalURL:input_type -> shortlink.GetOriginalURLRequest
	4,  // 5: shortlink.ShortLinkService.CreateShortURLBatch:input_type -> shortlink.CreateShortURLBatchRequest
	8,  // 6: shortlink.ShortLinkService.GetUserURLs:input_type -> shortlink.GetUserURLsRequest
	11, // 7: shortlink.ShortLinkService.DeleteUserURLs:input_type -> shortlink.DeleteUserURLsRequest
	13, // 8: shortlink.ShortLinkService.Ping:input_type -> shortlink.PingRequest
	15, // 9: shortlink.ShortLinkService.GetStats:input_type -> shortlink.GetStatsRequest
	1,  // 10: shortlink.ShortLinkService.CreateShortURL:output_type -> shortlink.CreateShortURLResponse
	3,  // 11: shortlink.ShortLinkService.GetOriginalURL:output_type -> shortlink.GetOriginalURLResponse
	5,  // 12: shortlink.ShortLinkService.CreateShortURLBatch:output_type -> shortlink.CreateShortURLBatchResponse
	9,  // 13: shortlink.ShortLinkService.GetUserURLs:output_type -> shortlink.GetUserURLsResponse
	12, // 14: shortlink.ShortLinkService.DeleteUserURLs:output_type -> shortlink.DeleteUserURLsResponse
	14, // 15: shortlink.ShortLinkService.Ping:output_type -> shortlink.PingResponse
	16, // 16: shortlink.ShortLinkService.GetStats:output_type -> shortlink.GetStatsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_shortlink_proto_init() }
func file_proto_shortlink_proto_init() {
	if File_proto_shortlink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortlink_proto_rawDesc), len(file_proto_shortlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortlink_proto_goTypes,
		DependencyIndexes: file_proto_shortlink_proto_depIdxs,
		MessageInfos:      file_proto_shortlink_proto_msgTypes,
	}.Build()
	File_proto_shortlink_proto = out.File
	file_proto_shortlink_proto_goTypes = nil
	file_proto_shortlink_proto_depIdxs = nil
}
